//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommunityHubb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public string Author { get; set; }
        public System.DateTime Date { get; set; }
        public int AutorId { get; set; }
        public int CommunityId { get; set; }
        public string CommunityName { get; set; }
    
        public virtual Community Community { get; set; }
        public virtual User User { get; set; }
    }
}
