//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommunityHubb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reaction
    {
        public int Id { get; set; }
        public int postId { get; set; }
        public int userId { get; set; }
        public bool isReply { get; set; }
        public bool isLike { get; set; }
        public Nullable<int> replyId { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual Reply Reply { get; set; }
        public virtual User User { get; set; }
    }
}
